### ISSUE TITLE
Saving the game, and using the inventory system

### ISSUE THREAD

**Issue by J-Vaughan** [KaptainKaleb/Adventure-Adventure-Adventure#6]
The inventory, progress, and general info will be saved in a text file named `savegame.txt` and so far I can write to the file and read from the file but I do not know how to modify lines in the file. This will concern `user.py` and `aaa.py`.

**Comment by KaptainKaleb** [comment]
Yeah, I have no idea how to do that

**Comment by J-Vaughan** [comment]
I'll be back
