### ISSUE TITLE
Simple formatting job

### ISSUE THREAD

**Issue by J-Vaughan** [KaptainKaleb/Adventure-Adventure-Adventure#7]
I screwed up in `user.py`. I need someone to go in, and change every instance of

    global something = userInfo[number]       # Comment
    global somethingelse = userInfo[number2]  # Comment2

to something along the lines of 

    global something
    global somethingelse

    something = userInfo[number]        # Comment
    somethingelse = userInfo[number2]   # Comment2

Thanks! Try and keep the comments, too.

**Comment by KaptainKaleb** [comment]
Fixed this Issue in commit bd045d85a5c7555f0ec2918472999cfc1bb191ab
